apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../rollouts-base
- infrastructure.yaml
- frontend-rollout.yaml
- ingress.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

# tutaj trzeba będzie zmienić na target kind Rollout pewnie.
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Rollout
    labelSelector: app.kubernetes.io/part-of=booking-microservices

images:
- name: k8smaestro/argo-rollouts-demo
  newTag: green

